# Generated by Django 3.2.7 on 2021-10-08 10:15

from django.db import migrations, models
import varfish.utils


class Migration(migrations.Migration):

    dependencies = [
        ("importer", "0008_variantsetimportinfo_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="caseimportinfo",
            name="release",
            field=models.CharField(default="GRCh37", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="caseimportinfo", name="pedigree", field=varfish.utils.JSONField(),
        ),
    ]
